### ISSUE TITLE
Make boost usage optional

### ISSUE THREAD

**Issue by ilopit** [santaclose/ImGuiColorTextEdit#6]
Hey! 

What do you think about making usage boost optional?

**Comment by santaclose** [comment]
what alternative do you suggest? the std implementation seems not to work properly (Microsoft STL I guess), saw stack overflows many times when running the search function.

**Comment by ilopit** [comment]
Hmm... I see your point. I am not a fan of regex, can't help. I am just afraid that bringing boost by default will complicate this library.

**Comment by ilopit** [comment]
maybe we can guard boost with #IFDEFS?

**Comment by santaclose** [comment]
the thing is, what should we use if not boost regex? We need regex for syntax highlighting. The library was added as a submodule and is being compiled from source, so imo shouldn't really be a problem. Are you having any issues with it?

**Comment by 3O11** [comment]
I don't fully understand the way regex is used in this code, but if it's really necessary to pull in a dependency, wouldn't it be better to use something like [CTRE](https://github.com/hanickadot/compile-time-regular-expressions) instead? There would be potential for better performance and since the library has a single-header version, it could be included directly in the repo, instead of using clunky git features like submodules.

**Comment by santaclose** [comment]
compile time regex sounds good for syntax highlighting yeah. I might look at it in the future, and you're of course welcome to open a pull request. Why do you think submodules are a clunky feature btw? (just curious)

**Comment by 3O11** [comment]
I'm planning on looking into it at some point, I just haven't had the time yet, unfortunately. I'll try to implement it and open a pull request when I manage to find enough time.

As for submodules, it's mostly just personal preference, since I've had some issues when using them. Specifically moving them around in the repo, updating the dependencies to new versions, and issues when the submodule path conflicts with an existing directory on a different branch. I usually resolve source dependencies with CMake's FetchContent, but I understand that's not ideal, since it would force the users to use a specific build system.

**Comment by santaclose** [comment]
thanks for the info!

**Comment by ilopit** [comment]
> Try to use google repo

**Comment by ilopit** [comment]
I guess we can close it
